appStartup:
  enabled: false
appSize:
  enabled: false

flows:
 - "**"

executionOrder:
  continueOnFailure: false
  flowsOrder:
    - "Sync Critical Path test: Data can be synced - Add data"
    - "Sync Critical Path test: Data can be synced - Verify data"